config/routes.rb
Reminders::Application.routes.draw do
  #root 'welcome#show'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  root to: 'sessions#new'
  resource :session, only: :destroy
  resources :spaces, only: :index do
    resources :reminders
  end
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  validates_presence_of :subject, :body
  validates :days_before, numericality: {greater_than_or_equal_to: 1}
  validates :bcc, email: true, allow_blank: true
  validate :markup_valid?

  scope :active, ->() { where(deactivation_reason: nil) }

  def space
    @space ||= Space.find(space_id, access_token)
  end

  def active?
    !deactivation_reason?
  end

  def markup_valid?
    Liquid::Template.parse body
    rescue Liquid::SyntaxError => e
      errors.add :body, e.message
  end

  def deactivate(reason)
    update_attribute :deactivation_reason, reason
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  helper_method :space

  def index
    if space.reminders.any?
      @reminders = space.reminders
    else
      redirect_to new_space_reminder_path(space)
    end
  end

  def new
    @reminder = Reminder.new from_email: space.email
  end

  def edit
    @reminder = space.reminders.find params[:id]
  end

  def create
    @reminder = space.reminders.build reminder_params
    @reminder.access_token = current_user.access_token
    if params[:commit] == 'Preview'
      preview @reminder, 'new'
    else
      if @reminder.save
        redirect_to space_reminders_path(space)
      else
        render 'new'
      end
    end
  end

  def update
    @reminder = space.reminders.find params[:id]
    @reminder.attributes = reminder_params
    if params[:commit] == 'Preview'
      preview @reminder, 'edit'
    else
      if @reminder.save
        redirect_to space_reminders_path(space), notice: 'Reminder changed.'
      else
        render 'edit'
      end
    end
  end

  def destroy
    reminder = space.reminders.find params[:id]
    reminder.destroy
    redirect_to space_reminders_path(space), notice: 'Reminder removed.'
  end

  private

  def reminder_params
    params[:reminder].permit(:subject, :body, :days_before, :bcc, :from_email)
  end

  def preview(reminder, action)
    if reminder.valid?
      @action = action
      render 'preview'
    else
      render action
    end
  end

  def space
    @space ||= current_user.spaces.find{|space| space.to_param == params[:space_id]}
  end
end

app/views/reminders/_edit_form.html.erb
<%= simple_form_for reminder, url: space_reminder_path(space, reminder), html: {class: 'form-horizontal'} do |f| %>
  <%= render 'form', f: f %>
  <div class="form-actions">
    <%= f.button :submit, value: 'Change Reminder', class: 'btn-primary' %>
    <%= f.button :submit, value: 'Preview' %>
  </div>
<% end %>

app/views/reminders/_form.html.erb
<%= f.input :from_email, label: 'Sender Email', input_html: {type: 'email'},
  hint: "Address from which to send the reminder. Leave blank for space's default address." %>
<%= f.input :subject, label: 'Email subject' %>
<%= f.input :bcc, label: 'Bcc', hint: "Send a copy of each email to this address" %>
<%= f.input :body, label: 'Email body',
  hint: "You can use <a href=\"http://docs.shopify.com/themes/liquid-documentation/basics\">Liquid</a> markup here:<br/><em>{{plan.name}}</em> will be replaced with the plan's name.<br/> <i>{{plan.price | money}}</i> will print out the plan's price.<br/> You can also use: <i>plan.currency</i>, <i>plan.extras</i> (where each extras has a <i>name</i> and a <i>price</i> field) <i>days</i> (no. of days until invoice is sent) and any of <i>member.address.name/member.address.first_name/company/address/city/state/post_code/country</i>.".html_safe,
  input_html: {rows: 9, value: f.object.body.blank? ? default_body : f.object.body, class: 'input-xxlarge input-block-level'} %>
<%= f.input :days_before, hint: 'Send the email x days before the invoice is due.', input_html: {min: 1} %>

app/views/reminders/_new_form.html.erb
<%= simple_form_for reminder, url: space_reminders_path(space), html: {class: 'form-horizontal'} do |f| %>
  <%= render 'form', f: f %>
  <div class="form-actions">
    <%= f.button :submit, value: 'Set Reminder', class: 'btn-primary' %>
    <%= f.button :submit, value: 'Preview' %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<div class="page-header">
  <h1>Change Reminder</h1>
</div>

<%= render 'edit_form', reminder: @reminder %>

app/views/reminders/index.html.erb
<div class="page-header">
  <h1>Reminders for <%= space.subdomain %></h1>
  <p class="lead">Here you can add/remove reminders.</p>
</div>

<ul class="unstyled">
  <% @reminders.each do |reminder| %>
    <li class="<%= 'inactive' if !reminder.active? %>">
      <h3>
        <div style="float: right">
          <%= link_to 'Edit', edit_space_reminder_path(space, reminder), class: 'btn' %>
          <%= link_to 'Remove', space_reminder_path(space, reminder), method: :delete, confirm: 'Really remove this reminder?', class: 'btn btn-danger' %>
        </div>
        <%= reminder.subject %>
        <small>(<%= pluralize reminder.days_before, 'day before', 'days before' %>)</small>
      </h3>
      <% if !reminder.active? %>
        Reminder has been deactivated due to an error. Plesae contact support.
      <% end %>
    </li>
  <% end %>
</ul>

<p><%= link_to 'Add Reminder', new_space_reminder_path(space), class: 'btn btn-primary' %></p>

app/views/reminders/new.html.erb
<div class="cb-section cb-section--padded bg--gray-4">
	<div class="cb-container">
		  <h1>New Reminder</h1>
	  	<p class="lead">Adding a reminder will send an email to each member <em>x</em> days before an invoice is due.</p>
	</div>
</div>
<div class="cb-section">
	<div class="cb-container">

<%= render 'new_form', reminder: @reminder %>

	</div>
</div>

app/views/reminders/preview.html.erb
<div class="page-header">
  <h1>Reminder Preview</h1>
</div>

  <pre><%= render_liquid(sample_membership, @reminder) %></pre>

<%= render "#{@action}_form", reminder: @reminder %>